### ISSUE TITLE
Failed to build on cordova-ios 4.0.0 and wkwebview-engine

### ISSUE THREAD

**Issue by si-ro** [shazron/KeychainPlugin#24]
I am currently trying to use the cordova-ios 4.0.0 (alpha test version) and cordova-plugin-wkwebview-engine.
I attempt to install the latest version of Keychain Plugin, but build fails.

Steps to Reproduce:

1. Create a Cordova Project.  
<pre>
cordova create wkwvtest my.project.id wkwvtest
cd wkwvtest
cordova platform add https://github.com/apache/cordova-ios.git#master
cordova plugin add https://github.com/apache/cordova-plugin-wkwebview-engine.git#master
cordova plugin add https://github.com/shazron/KeychainPlugin.git
</pre>
2. Deploy the app on a default iOS emulator.
<pre>
cordova emulate ios
</pre>
3. The following error occurred.
<pre>
/tmp/wkwvtest/platforms/ios/wkwvtest/Plugins/com.shazron.cordova.plugin.keychainutil/CDVKeychain.m:27:33: error: 
      no visible @interface for 'CDVPlugin' declares the selector
      'initWithWebView:'
    self = (CDVKeychain*)[super initWithWebView:(UIWebView*)theWebView];
                          ~~~~~ ^~~~~~~~~~~~~~~
1 error generated.
</pre>

**Comment by si-ro** [comment]
Congratulations on cordova ios 4.0.0 release. Thanks.

But this keychain plugin still is not working...
Please help me to fix.

I tryed it out. 
```
cordova create hello com.example.hello "HelloWorld"
cd hello
cordova platform add ios@4.0.0
cordova plugin add cordova-plugin-wkwebview-engine
cordova emulate ios
```
The following error occurred.
```
/CDVKeychain.o
/Users/si-ro/git/hello/platforms/ios/HelloWorld/Plugins/com.shazron.cordova.plugin.keychainutil/CDVKeychain.m:27:33: error: no visible @interface for
      'CDVPlugin' declares the selector 'initWithWebView:'
    self = (CDVKeychain*)[super initWithWebView:(UIWebView*)theWebView];
                          ~~~~~ ^~~~~~~~~~~~~~~
1 error generated.


```

**Comment by softBarbarian** [comment]
I have the same problem running `cordova 6.0.0` 

```
/Plugins/com.shazron.cordova.plugin.keychainutil/CDVKeychain.m:27:33: error: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
    self = (CDVKeychain*)[super initWithWebView:(UIWebView*)theWebView];
                          ~~~~~ ^~~~~~~~~~~~~~~
1 error generated.

```

@shazron

**Comment by shazron** [comment]
Fixed in #25

**Comment by si-ro** [comment]
I appreciate all your help!
